---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shopping
spec:
  replicas: 3
  selector:
    matchLabels:
      name: shopping
  template:
    metadata:
      labels:
        name: shopping
    spec:
      containers:
        - name: shopping
          image: 304167758050.dkr.ecr.us-east-2.amazonaws.com/shopping:latest
          imagePullPolicy: Always
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: merchant
spec:
  replicas: 3
  selector:
    matchLabels:
      name: merchant
  template:
    metadata:
      labels:
        name: merchant
    spec:
      containers:
        - name: merchant
          image: 304167758050.dkr.ecr.us-east-2.amazonaws.com/merchant:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  selector:
    name: shopping
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-service
spec:
  selector:
    name: merchant
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
